// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cTjDwWLquKg5bAgGhxiPk8TUhsyZJJ8',
    appId: '1:744909509386:web:d98f90cdd6c2994373e0f3',
    messagingSenderId: '744909509386',
    projectId: 'crud-t-49063',
    authDomain: 'crud-t-49063.firebaseapp.com',
    storageBucket: 'crud-t-49063.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnVddsmcCmakcmQWeN979JawBm9oBJog',
    appId: '1:744909509386:android:33632d03459228a773e0f3',
    messagingSenderId: '744909509386',
    projectId: 'crud-t-49063',
    storageBucket: 'crud-t-49063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzxGXRc6aY13ByArYo8s_Vn7KwNXtFKcs',
    appId: '1:744909509386:ios:71fabd19aad1a5e473e0f3',
    messagingSenderId: '744909509386',
    projectId: 'crud-t-49063',
    storageBucket: 'crud-t-49063.appspot.com',
    iosBundleId: 'com.example.crudFirebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzxGXRc6aY13ByArYo8s_Vn7KwNXtFKcs',
    appId: '1:744909509386:ios:71fabd19aad1a5e473e0f3',
    messagingSenderId: '744909509386',
    projectId: 'crud-t-49063',
    storageBucket: 'crud-t-49063.appspot.com',
    iosBundleId: 'com.example.crudFirebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7cTjDwWLquKg5bAgGhxiPk8TUhsyZJJ8',
    appId: '1:744909509386:web:f5c21100a7d30e9173e0f3',
    messagingSenderId: '744909509386',
    projectId: 'crud-t-49063',
    authDomain: 'crud-t-49063.firebaseapp.com',
    storageBucket: 'crud-t-49063.appspot.com',
  );
}
